name: Liblouis
description: An open-source braille translator and back-translator.
markdown: kramdown
highlighter: rouge
url: http://www.liblouis.org
baseurl: ""
gems:
  - jekyll-sitemap
exclude: 
  - README.md
defaults:
  - 
    scope:
      path: "" # all pages should have layout default by default
      type: "page"
    values:
      layout: "default"
  - 
    scope:
      path: "" # all posts should have layout post by default
      type: "post"
    values:
      layout: "post"
sass:
    style: expanded
